### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by fb-sean** [microlinkhq/spotify-url-info#119]
**Describe the bug**
When I try to do what the readme say I get a error.

**Your Code**
```
const fetch = require('isomorphic-unfetch')
const { getData, getPreview, getTracks, getDetails } = require('spotify-url-info')(fetch)
```

**Error Message**
0|bettyBOT  | TypeError: require(...) is not a function
0|bettyBOT  |     at Object.<anonymous> (/root/bettyBOT/base/audio-events.js:30:49)
0|bettyBOT  |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|bettyBOT  |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|bettyBOT  |     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|bettyBOT  |     at Module._load (node:internal/modules/cjs/loader:958:12)
0|bettyBOT  |     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|bettyBOT  |     at require (node:internal/modules/cjs/helpers:110:18)
0|bettyBOT  |     at Timeout._onTimeout (/root/bettyBOT/base/audio-player.js:62:5)
0|bettyBOT  |     at listOnTimeout (node:internal/timers:569:17)
0|bettyBOT  |     at process.processTimers (node:internal/timers:512:7) uncaughtException

**Comment by fb-sean** [comment]
Some new infos when I log

```
const spotifyUrlInfo = require("spotify-url-info");
console.log(spotifyUrlInfo);
```

I get this log:
![image](https://user-images.githubusercontent.com/71556073/228751847-397e48bc-0821-4e00-9ba1-f622b93ffb8d.png)

**Comment by fb-sean** [comment]
Okay the issue here was that NPM installed a old version even if npm said its @latest...

Thats how the file was https://github.com/microlinkhq/spotify-url-info/blob/3e49eb95321e249161a29f6936f9c074a9f539eb/src/index.js
