### ISSUE TITLE
Couldn't find scripts to get the data

### ISSUE THREAD

**Issue by Ilanox** [microlinkhq/spotify-url-info#125]
**Describe the bug**
using the ``getData()`` method, trying to actually get the data, but get this error every time, no matter which URL i'm using. Sometimes it does work and sometimes it doesn't, it is just randomly..

**Spotify URL(s)**
https://open.spotify.com/track/6TfBA04WJ3X1d1wXhaCFVT?si=08711e6dbb394d85

**My Code**
```js
    /**
     * Determine if a URL is for a track or a playlist.
     *
     * @param {string} url - Spotify URL.
     * @returns {Promise<{ type: string, data: any }>} - Object containing the type ("track" or "playlist") and the fetched data.
     * @throws {Error} If an error occurs during validation.
     */
    async getTrackType(url) {
        if (!url) throw new Error('You did not specify the URL of the Spotify song!');

        // Assuming this.validateURL() is a method that validates the Spotify URL.

        await this.validateURL(url);

        const data = await getData(url, {
            headers: {
                'user-agent': 'bingbot'
            }
        });

        return {
            type: data.type,
            data: data
        };
    }
```

**Error Message**
```error
Error while queuing Spotify track/playlist: TypeError: Couldn't find scripts to get the data.
Please report the problem at https://github.com/microlinkhq/spotify-url-info/issues.
    at throwError (/home/ilan/Documents/Edvin Music Bot/node_modules/spotify-url-info/src/index.js:24:9)
    at parseData (/home/ilan/Documents/Edvin Music Bot/node_modules/spotify-url-info/src/index.js:31:37)
    at /home/ilan/Documents/Edvin Music Bot/node_modules/spotify-url-info/src/index.js:75:10
    at processTicksAndRejections (/home/ilan/Documents/Edvin Music Bot/lib/internal/process/task_queues.js:96:5)
    at async Spotify.getTrackType (/home/ilan/Documents/Edvin Music Bot/music/Spotify.js:169:22)
    at async Object.run (/home/ilan/Documents/Edvin Music Bot/commands/play.js:65:35) {stack: 'TypeError: Couldn't find scripts to get the d…ments/Edvin Music Bot/commands/play.js:65:35)', message: 'Couldn't find scripts to get the data.
Pleas…hub.com/microlinkhq/spotify-url-info/issues.'}```

**Comment by Kikobeats** [comment]
Can you try to print the HTML markup? Probably Spotify is doing some A/B testing so it's not the same all the time

**Comment by Ilanox** [comment]
> Can you try to print the HTML markup? Probably Spotify is doing some A/B testing so it's not the same all the time

What do you mean?

**Comment by Kikobeats** [comment]
I tried to reproduce this, but as much as I tried it worked fine to me.

For the next time you experience this, modify the code and add a line on top of this one:

https://github.com/microlinkhq/spotify-url-info/blob/master/src/index.js#L28

to store the HTML as a file, like this way:

```diff
+ require('fs').writeFileSync('index.html', JSON.stringify(html, null, 2))
const embed = parse(html)
```

With a code reproduction we can understand better what happened.

Feel free to open a new issue with the file 🙂

**Comment by ItsPerona** [comment]
> I tried to reproduce this, but as much as I tried it worked fine to me.
> 
> For the next time you experience this, modify the code and add a line on top of this one:
> 
> https://github.com/microlinkhq/spotify-url-info/blob/master/src/index.js#L28
> 
> to store the HTML as a file, like this way:
> 
> ```diff
> + require('fs').writeFileSync('index.html', JSON.stringify(html, null, 2))
> const embed = parse(html)
> ```
> 
> With a code reproduction we can understand better what happened.
> 
> Feel free to open a new issue with the file 🙂

I have the same issue, the error is:
`TypeError: Couldn't find scripts to get the data.
Please report the problem at https://github.com/microlinkhq/spotify-url-info/issues.
    at throwError (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:24:9)
    at parseData (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:32:37)
    at /home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:76:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Couldn't find scripts to get the data.
  Please report the problem at https://github.com/microlinkhq/spotify-url-info/issues.
      at throwError (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:24:9)
      at parseData (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:32:37)
      at /home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:76:10
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}`

The code is a simple `getPreview(text).then(data => {...` with a url of a spotify track, the error sometimes appears and sometimes not
