### ISSUE TITLE
TypeError: Couldn't find scripts to get the data.

### ISSUE THREAD

**Issue by ItsPerona** [microlinkhq/spotify-url-info#126]
**Describe the bug**
Just like issue #125, im using the getPreview() method with a url of a spotify track, the error sometimes appears and sometimes not.

**Spotify URL(s)**
https://open.spotify.com/intl-es/track/2HZLXBOnaSRhXStMLrq9fD?si=0c23f172ebba42fb

**Your Code**
```js
// Spotify
const SpotifyFetch = require('isomorphic-unfetch')
const { getData, getPreview, getTracks } = require('spotify-url-info')(SpotifyFetch);

// More code

if (url.includes("spotify.com/") && url.includes("track/")) {
    getPreview(url).then(data => {  ...
```

**Error Message**
```bash
TypeError: Couldn't find scripts to get the data.
Please report the problem at https://github.com/microlinkhq/spotify-url-info/issues.
    at throwError (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:24:9)
    at parseData (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:32:37)
    at /home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:76:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> TypeError: Couldn't find scripts to get the data.
  Please report the problem at https://github.com/microlinkhq/spotify-url-info/issues.
      at throwError (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:24:9)
      at parseData (/home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:32:37)
      at /home/iperona/DiscordBot/GatoFeli/node_modules/spotify-url-info/src/index.js:76:10
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

**Comment by Kikobeats** [comment]
Can you try to debug it? what is the HTML markup associated with that URL?

**Comment by ItsPerona** [comment]
What do you mean? I use the package in a discord bot in javascript and node

**Comment by Kikobeats** [comment]
I suspect this is related with the HTML get from from the fetch request.

For debugging this, I released `spotify-url-info@3.2.12` which exposes `error.html`.

Can you do something like this?

```js
try {
    const data = await getPreview(url)
} catch(error) {
    const filepath = `${require('os').tmpdir()}/${url}.html`
    require('fs').writeFileSync(filepath, error.html)
    console.log('debug file at', filepath)
}
```

Then upload the file to https://gist.github.com/ or whatever so we can determine what's happening 🙂

**Comment by ItsPerona** [comment]
Done, when this error occurs again I will post it
